// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo-HvLCwxsv3CJ4yRgar8RHGOzUQKjHgg',
    appId: '1:600714684660:web:37e56f9edaac7830f256a1',
    messagingSenderId: '600714684660',
    projectId: 'flutter-app-yiarth',
    authDomain: 'flutter-app-yiarth.firebaseapp.com',
    storageBucket: 'flutter-app-yiarth.firebasestorage.app',
    measurementId: 'G-D3TXCTE35X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR00Nm8ujgKyhg83tkjtpkeQ9lKZGUVmE',
    appId: '1:600714684660:android:b770a038ad9ac1d1f256a1',
    messagingSenderId: '600714684660',
    projectId: 'flutter-app-yiarth',
    storageBucket: 'flutter-app-yiarth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIPEoR4slrHTwsAyQFl8gEixVMQpGAtyI',
    appId: '1:600714684660:ios:a8769ac1a59301e7f256a1',
    messagingSenderId: '600714684660',
    projectId: 'flutter-app-yiarth',
    storageBucket: 'flutter-app-yiarth.firebasestorage.app',
    iosBundleId: 'com.example.fleetlive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIPEoR4slrHTwsAyQFl8gEixVMQpGAtyI',
    appId: '1:600714684660:ios:a8769ac1a59301e7f256a1',
    messagingSenderId: '600714684660',
    projectId: 'flutter-app-yiarth',
    storageBucket: 'flutter-app-yiarth.firebasestorage.app',
    iosBundleId: 'com.example.fleetlive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo-HvLCwxsv3CJ4yRgar8RHGOzUQKjHgg',
    appId: '1:600714684660:web:0998618cbb22b17bf256a1',
    messagingSenderId: '600714684660',
    projectId: 'flutter-app-yiarth',
    authDomain: 'flutter-app-yiarth.firebaseapp.com',
    storageBucket: 'flutter-app-yiarth.firebasestorage.app',
    measurementId: 'G-YM1WV4PNQS',
  );

}